export const AUTH_TOPICS = {
  USER_OTP_CREATED: "USER_OTP_CREATED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
};

export const PRODUCT_TOPICS = {
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_DELETED: "PRODUCT_DELETED",
};
